name:                css-normalize
version:             0.1.0.0
license:             BSD3
author:              "Szymon Kozłowski"
maintainer:          "szymek.kozlowski1@gmail.com"

description:         Package for normalizing CSS files.

dependencies:
- base
- css-syntax
- megaparsec >= 7 && < 8
- text
- containers
- optparse-applicative

library:
  source-dirs: src

ghc-options:
    - -Wall
    - -Wincomplete-patterns
    - -Woverlapping-patterns
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -fno-warn-orphans

executables:
  cssn:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - css-normalize

tests:
  css-normalize-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - css-normalize
    - hspec
    - hspec-megaparsec
